/**
 * Dial channel adapter for NanoClaw v2.
 *
 * Dial (https://getdial.ai) gives an agent a real phone number — SMS and
 * AI-handled voice calls. Native adapter (no Chat SDK bridge):
 *
 *   - Outbound SMS via the official `@getdial/sdk` (`DialClient.sendMessage`).
 *   - Inbound via Dial's documented CLI command-target
 *     (docs.getdial.ai/integrations/agent-clients/nanoclaw). NanoClaw has no
 *     inbound HTTP webhook, so the adapter registers a small handler script
 *     with Dial's `listen` daemon; the daemon runs it per event with the event
 *     JSON as the final arg, the handler spools it to a directory the adapter
 *     watches, and `message.received` / `call.ended` route through the normal
 *     entity model so replies flow back out over SMS.
 *
 * The API key + from-number come from Dial's auth file (written by `dial
 * onboard`). If there's no key the factory returns null and the channel is
 * skipped.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';

import { DialClient } from '@getdial/sdk';

import type { ChannelAdapter, ChannelDefaults, ChannelSetup, InboundMessage, OutboundMessage } from './adapter.js';
import { registerChannelAdapter } from './channel-registry.js';
import { DATA_DIR } from '../config.js';
import { readEnvFile } from '../env.js';
import { log } from '../log.js';

/** Longest SMS body sent in one shot; longer text is chunked. */
const MAX_CHUNK = 1500;

/** Dedup window — the listen daemon retries a failed handler invocation once. */
const DEDUP_TTL_MS = 5 * 60_000;

/** Dial listen-daemon event envelope (the subset we consume). */
interface DialEventEnvelope {
  id?: string;
  type?: string;
  createdAt?: string;
  data?: Record<string, unknown>;
}

interface DialConfig {
  apiKey: string;
  /** E.164 to send from; '' → let the server use the account's default number. */
  fromNumber: string;
  cliPath: string;
}

function chunkText(text: string, limit: number): string[] {
  const chunks: string[] = [];
  let remaining = text;
  while (remaining.length > 0) {
    if (remaining.length <= limit) {
      chunks.push(remaining);
      break;
    }
    let splitAt = remaining.lastIndexOf('\n', limit);
    if (splitAt <= 0) splitAt = limit;
    chunks.push(remaining.slice(0, splitAt));
    remaining = remaining.slice(splitAt).replace(/^\n/, '');
  }
  return chunks;
}

/**
 * The handler script Dial's listen daemon runs per event: it spools the event
 * JSON (passed as the final positional argument) into a directory the adapter
 * watches, written atomically (temp + rename) so the watcher never reads a
 * partial file. Runs with a clean env (PATH + HOME only), so the spool dir is
 * baked in as an absolute path.
 */
function handlerScript(spoolDir: string): string {
  return `#!/usr/bin/env bash
# Auto-generated by NanoClaw's Dial channel adapter (src/channels/dial.ts).
# Dial CLI command target: https://docs.getdial.ai/integrations/methods/cli-command-target
set -euo pipefail
[ "$#" -eq 0 ] && exit 0
spool=${JSON.stringify(spoolDir)}
mkdir -p "$spool"
event="\${!#}"   # value of the last positional parameter = the event JSON
tmp="$spool/.tmp.$$.\${RANDOM}"
printf '%s' "$event" > "$tmp"
mv -f "$tmp" "$spool/$(date +%s).$$.\${RANDOM}.json"
exit 0
`;
}

/**
 * Dial has no group chats: every conversation is 1:1 between the account's
 * number and a remote number, so every inbound is a DM (isMention:true,
 * isGroup:false) and mentions are 'dm-only'. Unknown senders default to
 * 'request_approval' — anyone can text a phone number.
 */
const DIAL_DEFAULTS: ChannelDefaults = {
  dm: { engageMode: 'pattern', engagePattern: '.', threads: false, unknownSenderPolicy: 'request_approval' },
  group: { engageMode: 'pattern', engagePattern: '.', threads: false, unknownSenderPolicy: 'request_approval' },
  mentions: 'dm-only',
};

export function createDialAdapter(config: DialConfig): ChannelAdapter {
  const client = new DialClient({ apiKey: config.apiKey });
  const spoolDir = path.join(DATA_DIR, 'dial', 'inbound');
  const handlerPath = path.join(DATA_DIR, 'dial', 'handle-dial-event.sh');

  let setup: ChannelSetup | null = null;
  let connected = false;
  let watcher: fs.FSWatcher | null = null;
  let pollTimer: ReturnType<typeof setInterval> | null = null;
  let draining = false;
  const seen = new Map<string, number>();

  /** True if this event id was already routed within the dedup window. */
  function seenBefore(id: string): boolean {
    const now = Date.now();
    for (const [k, ts] of seen) if (now - ts > DEDUP_TTL_MS) seen.delete(k);
    if (seen.has(id)) return true;
    seen.set(id, now);
    return false;
  }

  /** Route one inbound event — SMS text and ended-call notifications only. */
  function routeEvent(env: DialEventEnvelope): void {
    if (!setup) return;
    if (env.id && seenBefore(env.id)) return;
    const data = env.data ?? {};

    let peer = '';
    let text = '';
    if (env.type === 'message.received') {
      if (data.source && data.source !== 'external') return; // ignore Dial-synthesized test SMS
      peer = typeof data.from === 'string' ? data.from : '';
      text = typeof data.body === 'string' ? data.body : '';
    } else if (env.type === 'call.ended') {
      const outbound = data.direction === 'outbound';
      const other = outbound ? data.to : data.from;
      peer = typeof other === 'string' ? other : '';
      const dur = typeof data.durationSeconds === 'number' ? `, ${data.durationSeconds}s` : '';
      const callId = typeof data.callId === 'string' ? data.callId : '';
      const transcript =
        data.transcriptAvailable && callId ? ` Run \`dial call get ${callId}\` for the transcript.` : '';
      text = `[Voice call ${outbound ? 'outbound' : 'inbound'} ${data.status ?? 'ended'}${data.canceled ? ' (canceled)' : ''}${dur}.${transcript}]`;
    } else {
      return;
    }
    if (!peer || !text) return;

    const id = [data.messageId, data.callId, env.id].find((v): v is string => typeof v === 'string' && !!v);
    const msg: InboundMessage = {
      id: id ?? peer,
      kind: 'chat',
      content: { text, sender: peer, senderId: `dial:${peer}`, senderName: peer },
      isMention: true,
      isGroup: false,
      timestamp: env.createdAt || new Date().toISOString(),
    };
    void Promise.resolve(setup.onInbound(peer, null, msg)).catch((err) =>
      log.error('Dial: onInbound failed', { peer, err }),
    );
    log.info('Dial inbound routed', { peer, type: env.type });
  }

  function processSpoolFile(file: string): void {
    const full = path.join(spoolDir, file);
    let raw: string;
    try {
      raw = fs.readFileSync(full, 'utf8');
    } catch {
      return; // already consumed by a concurrent tick
    }
    try {
      fs.unlinkSync(full);
    } catch {
      /* best-effort */
    }
    if (!raw.trim()) return;
    try {
      routeEvent(JSON.parse(raw) as DialEventEnvelope);
    } catch (err) {
      log.warn('Dial: unparseable spooled event', { file, err });
    }
  }

  /** Drain the spool directory once, in filename (roughly chronological) order. */
  function drainSpool(): void {
    if (draining) return;
    draining = true;
    try {
      for (const f of fs
        .readdirSync(spoolDir)
        .filter((f) => f.endsWith('.json'))
        .sort()) {
        processSpoolFile(f);
      }
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') log.debug('Dial: spool drain error', { err });
    } finally {
      draining = false;
    }
  }

  /**
   * Best-effort: write the handler script and register it as a Dial CLI command
   * target. Failures are logged, never thrown — the adapter keeps watching the
   * spool regardless, and the wizard/skill can establish this out of band.
   */
  function ensureCommandTarget(): void {
    try {
      fs.mkdirSync(path.dirname(handlerPath), { recursive: true });
      fs.writeFileSync(handlerPath, handlerScript(spoolDir), { mode: 0o755 });
      fs.chmodSync(handlerPath, 0o755);
    } catch (err) {
      log.warn('Dial: could not write command-target handler', { handlerPath, err });
      return;
    }
    try {
      const listed = execFileSync(config.cliPath, ['local-target', 'list', '--json'], {
        encoding: 'utf8',
        timeout: 15_000,
      });
      if (!listed.includes(handlerPath)) {
        execFileSync(config.cliPath, ['local-target', 'add', 'cmd', handlerPath], { stdio: 'ignore', timeout: 15_000 });
        log.info('Dial: registered CLI command target', { handlerPath });
      }
    } catch (err) {
      log.warn(
        'Dial: could not register command target — check `dial` is on PATH (DIAL_CLI_PATH) and `dial listen install` has run',
        { err },
      );
    }
  }

  const adapter: ChannelAdapter = {
    name: 'dial',
    channelType: 'dial',
    supportsThreads: false,
    defaults: DIAL_DEFAULTS,

    async setup(cfg: ChannelSetup): Promise<void> {
      setup = cfg;
      fs.mkdirSync(spoolDir, { recursive: true });
      ensureCommandTarget();

      drainSpool(); // anything spooled while we were down
      try {
        watcher = fs.watch(spoolDir, () => drainSpool());
      } catch (err) {
        log.debug('Dial: fs.watch unavailable, relying on poll', { err });
      }
      pollTimer = setInterval(drainSpool, 2000); // fallback — fs.watch misses events on some mounts

      connected = true;
      log.info('Dial channel connected', { fromNumber: config.fromNumber || '(account default)' });
    },

    async teardown(): Promise<void> {
      connected = false;
      watcher?.close();
      watcher = null;
      if (pollTimer) clearInterval(pollTimer);
      pollTimer = null;
      log.info('Dial channel disconnected');
    },

    isConnected(): boolean {
      return connected;
    },

    async deliver(platformId: string, _threadId: string | null, message: OutboundMessage): Promise<string | undefined> {
      const content = message.content as Record<string, unknown> | string | undefined;
      const text =
        typeof content === 'string'
          ? content
          : content && typeof content === 'object' && typeof content.text === 'string'
            ? content.text
            : '';
      if (!text) return undefined;

      let lastId: string | undefined;
      for (const chunk of text.length <= MAX_CHUNK ? [text] : chunkText(text, MAX_CHUNK)) {
        try {
          const sent = await client.sendMessage({
            to: platformId,
            body: chunk,
            ...(config.fromNumber ? { fromNumber: config.fromNumber } : {}),
          });
          lastId = sent?.id ?? lastId;
        } catch (err) {
          log.error('Dial: sendMessage failed', { platformId, err });
        }
      }
      return lastId;
    },
  };

  return adapter;
}

// ---------------------------------------------------------------------------
// Self-registration
// ---------------------------------------------------------------------------

registerChannelAdapter('dial', {
  factory: () => {
    // Credentials come from Dial's own auth file (written by `dial onboard`).
    const authFile = path.join(
      process.env.XDG_DATA_HOME || path.join(homedir(), '.local', 'share'),
      'dial',
      'auth.v1.json',
    );
    let apiKey = '';
    let fromNumber = '';
    try {
      const auth = JSON.parse(fs.readFileSync(authFile, 'utf8')) as { apiKey?: string; phoneNumber?: string };
      apiKey = auth.apiKey ?? '';
      fromNumber = auth.phoneNumber ?? '';
    } catch {
      /* no auth file — not signed in */
    }
    if (!apiKey) {
      log.debug('Dial: not signed in (run `dial signup` + `dial onboard`), skipping channel');
      return null;
    }

    const env = readEnvFile(['DIAL_CLI_PATH']);
    const cliPath = process.env.DIAL_CLI_PATH || env.DIAL_CLI_PATH || 'dial';
    return createDialAdapter({ apiKey, fromNumber, cliPath });
  },
  defaults: DIAL_DEFAULTS,
});
